### ISSUE TITLE
Add streaming support

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#295]
Streaming support would be a good addition.

**Comment by dapphp** [comment]
Hi @abraham , For a few years now I've had some efficient code I use for the streaming API.  It supports gzip, uses cURL for handling connections and streaming, OAuth, follows all the guidelines I'm aware of (exponential backoff, error handling [temporary vs permanent]) and so forth.

If you're interested in taking a look and discussing before I publish the code anywhere, feel free to message me.

I'd be willing to contribute it to your library rather than release something separate and help offer support for that portion as well.

**Comment by salvob41** [comment]
This would be an awesome addition, do you guys have any update on this?

**Comment by dapphp** [comment]
@salvob41 If you're willing to work with me and provide feedback to test my library, I'd be happy to touch it up and post it publicly.

It uses it's own OAuth library, has some basic classes for API calls, and would basically be completely independent of this library.  I'm by no means trying to replace or hijack abraham's version in the PHP ecosystem (I just needed streaming/firehose and it was kinda a hobby project to do the rest).  Hence why it's been private for basically 5 years :)

**Comment by abraham** [comment]
Related #684

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
