### ISSUE TITLE
Support the Ads API

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#382]
This would probably be a breaking change and would likely result in an API that looks something like this.

```
$twt = new TwitterOAuth(...);
$ads = $twt->ads->get(...); // Ads request
$statuses = $twt->api->get(...); // REST API request
```

**Comment by esthezia** [comment]
Hi Abraham! For now, you could only change TwitterOAuth.php and access `API_HOST` by `static::API_HOST` instead of `self::API_HOST`, and the same for `API_VERSION`. This, to be able to overwrite these in an extending class. And this seems to suffice to be able to use this library for working with Ads API.

I've done this locally and it works with only these changes made.

**Comment by rossbg** [comment]
Hello,

I think this should be top pri :) Any timeframe to share? Thanks :)

**Comment by idlikesometea** [comment]
Exactly what should I change to connect to ADS Api? I've changed the self to statics and the API_HOST  to https://ads-api.twitter.com but i keep getting a ROUTE_NOT_FOUND error. Any clue? Thanks in advance

**Comment by rossbg** [comment]
you should change API_VERSION to "0"

**Comment by idlikesometea** [comment]
Thanks!

**Comment by abraham** [comment]
Moving to #684
