### ISSUE TITLE
Question: How to check if user has authorized application?

### ISSUE THREAD

**Issue by davout1806** [abraham/twitteroauth#399]
Based on the demo https://github.com/abraham/twitteroauth-demo I've got my code working for the general case. 

What I can figure out is when user is still logged in (i.e. has not cleared session) but has - via twitter interface - revoked access for the application. I want to be check if the user has authorized access. 

Thanks.

**Comment by abraham** [comment]
[GET account/verify-credentials](https://dev.twitter.com/rest/reference/get/account/verify_credentials) is the common method to make sure an access_token is still valid. However since every API request requires authentication, you can validate if the access_token still works as long as you don't get 401 errors.

**Comment by davout1806** [comment]
Thank you very much.
