### ISSUE TITLE
Improve marketing and demo site

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#413]
https://mail.google.com/mail/u/0/#inbox/14f573225b3b3d5b

**Comment by kinoute** [comment]
Hey,

Sorry if you already spotted this, just a little issue but I think you forgot to remove a comma in the demo/marketing website when explaining how to upload medias (in the `$parameters` array):

`$media2 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten2.jpg']);
$parameters = [
    'status' => 'Meow Meow Meow',
    'media_ids' => implode(',', [$media1->media_id_string, $media2->media_id_string]),
];`

There is no need for a comma here since there is no more value to add in the array (or I'm missing something?). This comma does not appear in your tests file.

Nothing really important anyway.

Cheers

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
