### ISSUE TITLE
Name lookup timed out

### ISSUE THREAD

**Issue by Agistopolis** [abraham/twitteroauth#505]
Hi Abraham,

I am using twitteroauth to allow users login with Twitter on our website. We have received the following error.

Abraham\TwitterOAuth\TwitterOAuthException: name lookup timed out in Abraham\TwitterOAuth\TwitterOAuth->request()

Our website is hosted on a VPS using Goggle DNS.

Any suggestions? 
Thanks

**Comment by abraham** [comment]
If you are ok with requests taking longer you can configure the amount of time to wait before a timeout. E.g. this will allow 10 seconds for the DNS/connection and an additional 5 seconds for the response for a total allowed time of 15 seconds.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setTimeouts(10, 15);
```

Otherwise you might want to catch the exception and immediately try a second time.

**Comment by Agistopolis** [comment]
Awesome thank you Abraham (y)
