### ISSUE TITLE
Failed to connect to api.twitter.com port 443

### ISSUE THREAD

**Issue by AbhayLodhi** [abraham/twitteroauth#517]
Dear Sir i use src folder and autoload.php file with https://github.com/sohaibilyas/twitter-api-php project i make all the steps perfectly according to sohaibilyas youtube video. his project work fine in video but when i try to run my projects the it show me the following error.

> Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443: Connection refused' in /home/u377242486/public_html/s/src/TwitterOAuth.php:408 Stack trace: #0 /home/u377242486/public_html/s/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/u377242486/public_html/s/src/TwitterOAuth.php(135): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/u377242486/public_html/s/index.php(12): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/u377242486/public_html/s/src/TwitterOAuth.php on line 408

Sir plz help me Thnx

**Comment by abraham** [comment]
The error `Failed to connect to api.twitter.com port 443: Connection refused` generally means that your server can't connect to api.twitter.com. Sometimes that's caused by a firewall blocking connections, sometimes that's caused by your IP being blocked by Twitter, sometimes there is an ISP between your server and Twitter that is broken.

It's pretty much always not an issue with the TwitterOAuth library however.

Maybe the same issue as #513

**Comment by AbhayLodhi** [comment]
thanks sir for your help ..i have use that code on localhost its working. u was right that was server issue.
thank u again

**Comment by MosesKet** [comment]
> thanks sir for your help ..i have use that code on localhost its working. u was right that was server issue.
> thank u again

i have the same issue how were you able to resolve yours
