### ISSUE TITLE
How could i use (oauth/access_token) get user name or id through by correct authorization?

### ISSUE THREAD

**Issue by andyhua** [abraham/twitteroauth#529]
hello:) @abraham, how are you !
these days , i'm develop some api with your twitterauth , that cool.
and i'm doing this https://twitteroauth.com/redirect.php content success, i got these oauth_token and oauth_token_secret and users could doing authorizing...
but how can i get the twitter user info like name or uid ? , in actually i want the unique user id, i didn't found any doc or faqs from twitteroauth.com.
and fond some problam like
private function pharRunning() { return false; //return class_exists('Phar') && !empty(\Phar::running(false)); }
i'm fixed like that can be work.

$totken = $connection->oauth("oauth/access_token", ["oauth_verifier" => $oauth_verifier]);
and this place thow a exception message was 此功能暫時無法使用

thanks.
andyhua.

**Comment by abraham** [comment]
It's hard to tell. Do you have two issues? A problem you don't describe with `pharRunning` and the error `此功能暫時無法使用` from Twitter?

What is the problem with `pharRunning`?

此功能暫時無法使用 translates to "This feature is temporarily unavailable" for me so that's not something I can help with. Usually that means that Twitter has disabled something and it should come back. You should double check the step after https://twitteroauth.com/redirect.php on callback.php to make sure you are not missing anything though.

**Comment by andyhua** [comment]
ok, thank you very much , 
and i found this `pharRunning` was fixed in your release 0.7.2
