### ISSUE TITLE
media type unrecognized error when trying upload photos

### ISSUE THREAD

**Issue by MacGWik** [abraham/twitteroauth#572]
I have tried to use the code for uploading media + tweet it, and got a problem. 

The photo wasn't uploaded. I don't understand where's my fault. And here's my case
![image](https://user-images.githubusercontent.com/12266489/27025151-a0231034-4f83-11e7-865e-e0d9fa814177.png)
I put the photos on the root folder "TwitterAPI"

![image](https://user-images.githubusercontent.com/12266489/27025184-c8a7aad8-4f83-11e7-96b7-027bcbd83622.png)
Here's my code on post.php. Try to upload the photo and tweet it.

![image](https://user-images.githubusercontent.com/12266489/27025256-11fd3f90-4f84-11e7-9d96-a696ebb642da.png)
And this is all I got from the `$media1` and `$media2`.

It's an error ?

I have tried some other photos with different extension, but all of them get the same "media type unrecognized." error...

**Comment by mrbellek** [comment]
You might want to revoke those keys and generate new ones...

**Comment by abraham** [comment]
I'm guessing it's an issue with how you specify the file path. You are using `/TwitterAPI/file.ext` and `/file.ext` but it looks like the files are actually located at `/public_html/TwitterAPI/file.ext` and `/public_html/file.ext`.

**Comment by MacGWik** [comment]
It's still giving me the "media type unrecognized." error @abraham 
the revoke keys method is not working too @mrbellek 

Can we see what path that twitterAPI see when they try to upload the photos ?
Or maybe you have a sample working code for tweet + media, so I can see what's the different with mine

**Comment by MacGWik** [comment]
wait. the untitled.png is working by using this code 

`$media1 = $connection->upload('media/upload', ['media' => 'Untitled.png']);`

but the jpeg or jpg is not working.

is there's any restriction on the size of the media that I can upload @abraham ??

**Comment by abraham** [comment]
Yes, there are images restrictions.

https://dev.twitter.com/rest/media/uploading-media#imagerecs

**Comment by Hardik7538** [comment]
I am using twitter Api in node.js and I am still getting the error that media type is unrecognized

**Comment by carlitosz** [comment]
@Hardik7538 @MacGWik I ran into this issue as well, here is my solution:

I made an override of the `Client.php` and edited the method `postStatusWithMedia` as such:

```public function postStatusWithMedia(string $message, array $mediaPaths = [], $mediaType): string
    {
        $media_ids = [];
        foreach ($mediaPaths as $mediaPath) {
            $media = $this->client->upload('media/upload', ['media' => $mediaPath, 'media_type' => $mediaType], true);
            $media_ids[] = $media->media_id_string;
        }

        $parameters = [
            'status' => $message,
            'media_ids' => implode(',', $media_ids),
        ];

        $response = $this->client->post('statuses/update', $parameters);```

This line in particular was the one that I changed:

`$media = $this->client->upload('media/upload', ['media' => $mediaPath, 'media_type' => $mediaType], true);`

I included the "media_type" and the `true` flag so that the media can be uploaded chunked.*
If you take a look at `TwitterOAuth.php` the method `uploadMediaChunked` expects the `media_type` to be set. I set this manually and it worked perfectly when uploading video/mp4 types.

* https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-append

Hope this works for you!
