### ISSUE TITLE
Some questions please..

### ISSUE THREAD

**Issue by jackymode1** [abraham/twitteroauth#621]
How this work exactly? `statuses/home_timeline` I set this up and tweets were showing okay, but I noticed that "sometimes" it doesn't work, other times I see the tweets. I now don't see them but I created a new tweet just a second ago and suddenly that tweet is showing, only this new tweet but old tweets don't show up even when I set 5 tweets to display! Yesterday they all showed up so what's going on? 

Is this library using cache or something like that? If 10 users check my page is that mean 10 requests and if they refresh the page twice is it gonna be 20 requests to the API?

How can I set this to display 5 latest tweets cached for 5 hours?

Thank you..

**Comment by abraham** [comment]
`count` is more of max number. It will not always return that number of tweets. If you always want to have five you will have to increase the number to maybe 25 and then limit it to five locally.

The reason you sometimes don't get any back is because [GET statuses/home_timeline](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline) defaults `exclude_replies` to `true`. This means if the first five tweets are replies they will be included in the `count=five` but then removed before getting returned to your app. If you are OK with replies you can set that to false.
