### ISSUE TITLE
Video upload local not work

### ISSUE THREAD

**Issue by mohamedhassn** [abraham/twitteroauth#654]
Hello abraham, I use this code for upload video but it's not work, it's work only for upload images:
here my code:

```
<?php

require "init.php";

if ($_SERVER['REQUEST_METHOD'] != "POST") {
    die("Not Allowed");
}

$media_path = ($_FILES['media']['tmp_name'][0]);
$status = ($_POST['status']);

if ((!$media_path) and (!$status)) {
    die("Nothing to Post");
}

$media_id = "";
if ($media_path) {
    $media = $connection->upload('media/upload', ['media' => $media_path ]);
    $media_id = $media->media_id_string;
}
$parameters = [
    'status' => $status,
    'media_ids' => implode(',', [$media_id])
];
$result = $connection->post('statuses/update', $parameters);

header("location: index.php");
die();
```

**Comment by abraham** [comment]
If it's a video you almost certainly need to use the chunked upload API. Try

    $media = $connection->upload('media/upload', ['media' => $media_path ], true);

**Comment by CpHeat** [comment]
> If it's a video you almost certainly need to use the chunked upload API. Try
> 
> ```
> $media = $connection->upload('media/upload', ['media' => $media_path ], true);
> ```

Where would I had to look to find this info ? I had a hard time finding this and was stuck, but didn't want to come here asking a simple question that I should have been able to figure out by myself, I think I don't read docs the right way because I always struggle to find this kind of info (I don't have an academic past I learned alone so I guess I miss some good practices)
