### ISSUE TITLE
Twitter OAuth Pin Based Login HELP PLS

### ISSUE THREAD

**Issue by trphp** [abraham/twitteroauth#745]
Hello Abraham
<?php
$pin = "8837348";
session_start();

require_once 'common.php';
require_once 'twitteroauth-master/autoload.php';

use Abraham\TwitterOAuth\TwitterOAuth;

$request_token = [];  

if (isset($_REQUEST['oauth_token']) && $request_token['oauth_token'] !== $_REQUEST['oauth_token']) {
    die( 'Error!' );
}

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

$_SESSION['access_token'] = $connection->oauth("oauth/access_token", array("oauth_verifier" => "8837348"));

session_regenerate_id();

**Comment by abraham** [comment]
Using the PIN flow should be exactly like the [3-legged oauth flow](https://developer.twitter.com/en/docs/basics/authentication/overview/3-legged-oauth.html) with only a couple of minor differences. You can see a full live demo of the 3-legged flow at https://twitteroauth.com/redirect.php.

The changes you'll have to make:

1)  Use `'oob'` as the value of `OAUTH_CALLBACK`.

2) Use the PIN instead of the `oauth_verifier`.

~~~php
$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => "PIN HERE"]);
~~~

**Comment by abraham** [comment]
Don't post application secrets publicly. You'll want to reset those in the Twitter API dashboard. Nothing there looks wrong. The oauth_verifier value will change every time though.

**Comment by trphp** [comment]
Thank you very much abraham.
but I could not enter the pin based.

**Comment by trphp** [comment]
Can Abraham be the problem?
 
need to reconcile with request token pin ?

`i am still using it`
`![ekran alintisif](https://user-images.githubusercontent.com/30803537/51750953-a545ba80-20c4-11e9-92da-c1330b1e1c06.PNG)`

Can you help me some more?

**Comment by abraham** [comment]
That's a very old version of TwitterOAuth. I suggest updating and trying again.
