### ISSUE TITLE
tweet upload video error

### ISSUE THREAD

**Issue by abhishekpwebdev** [abraham/twitteroauth#771]
I am trying to post a tweet on twitter through twitter post API I am able to tweet the text and image successfully but I am facing an issue in posting the video.  I am following the chunked media process for video but it is giving the below error.

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => 324 [message] => Not valid video ) ) )

**Comment by abraham** [comment]
That sounds like an invalid video format. Make sure you video meets the requirements. https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices.html

**Comment by dalisalvador** [comment]
@abhishekpwebdev Have you solved this? I'm getting the same error and it's not the file size etc etc :(

**Comment by EazyServer** [comment]
After countless hours digging into this I found the culprit! 
turns out the video is not usually ready right after upload is complete! so you need to wait until the media is ready before adding it to a tweet.

![Screenshot 2020-06-14 at 14 55 04](https://user-images.githubusercontent.com/19202935/84595763-a14d4080-ae51-11ea-8db0-dd54474cf190.png)


I have added a [pull request](https://github.com/abraham/twitteroauth/pull/844) to notify maintainer of this issue
