### ISSUE TITLE
unhandled exceptions

### ISSUE THREAD

**Issue by Pappu420** [abraham/twitteroauth#772]
Consider this:

On Device A: User logged in on Twitter PHP App using the Twitter APIs

On Device B: User either changes his/her twitter password (and does not revoke access to the above app) OR User revokes access without changing the twitter  password

In either of these cases, in the session on Device A: 
Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: This feature is temporarily unavailable in Twitter-API-Login-PHP-master/src/TwitterOAuth.php:138
Stack trace:
#0 Twitter-API-Login-PHP-master/callback.php(10): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
#1 {main}
  thrown in Twitter-API-Login-PHP-master/src/TwitterOAuth.php on line 138

Line 138 is:         if ($this->getLastHttpCode() != 200) {
            throw new TwitterOAuthException($result);
        }

How to identify with TwitterAuth that either password is invalid OR user has revoked permission. (in case of already having logged in on the PHP APP_?

**Comment by abraham** [comment]
From the error side I don't think you can tell what the specific cause is other than just a generic unauthorized error. I would however expect that unauthorized errors for [POST oauth/access-token](https://developer.twitter.com/en/docs/basics/authentication/api-reference/access_token) to be very rare since that should only be used within a few seconds of the user authorizing access.
