### ISSUE TITLE
upload/media throws an exception when providing an http resource

### ISSUE THREAD

**Issue by williamlang** [abraham/twitteroauth#799]
private function uploadMediaNotChunked($path, array $parameters)
    {
        if (! is_readable($parameters['media']) ||
            ($file = file_get_contents($parameters['media'])) === false) {
            throw new \InvalidArgumentException('You must supply a readable file');
        }
        $parameters['media'] = base64_encode($file);
        return $this->http('POST', self::UPLOAD_HOST, $path, $parameters, false);
    }

is_readable on an http resource will be false while file_get_contents will return true. Because of this, uploading a file using a url will never work.

`echo is_readable('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png');`

`echo file_get_contents('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png');`

**Comment by abraham** [comment]
This is expected. Twitter does not support URLs for file uploads. The file has to be on your server and uploaded.

**Comment by williamlang** [comment]
I do this right now, though. And it works.

**Comment by abraham** [comment]
The library should not hide from the developer that a file is being downloaded to their server and then uploaded to Twitter. Previously if you had a large image on another server developers would use a URL and think that Twitter was getting the file directly. The library was updated to make it clear that the file must be on the developers server and be uploaded directly to Twitter.

#681 is tracking adding a file class where the developer can chose to use a file on disk, a remote file that will be temporarily downloaded, or some other means.

**Comment by williamlang** [comment]
Fair enough, thanks!

**Comment by JackWH** [comment]
This has caught people out using Laravel's [Twitter Notifications](https://github.com/laravel-notification-channels) package. Because Laravel abstracts the filesystem, it's not currently possible to attach an image if, for example, it's stored on AWS S3.

[In this issue thread](https://github.com/laravel-notification-channels/twitter/issues/64#issuecomment-962177448), I've suggested two simple fixes that could be made to the `uploadMediaNotChunked()` function which would resolve this. I'm not sure how far off #681 is, but this would be very helpful for Laravel users in the meantime...
