### ISSUE TITLE
Automatic status posting

### ISSUE THREAD

**Issue by pdjakow** [abraham/twitteroauth#818]
I'm trying to auto post my twitter account status (via linux/crontab), unfortunetaly without success:

require 'twitteroauth/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', consumerkey);
define('CONSUMER_SECRET', mysecretkey);
define('OAUTH_CALLBACK', 'https://meteomodel.pl/callback.php');

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
print_r ($request_token);
$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];

$statues = $connection->post("statuses/update", ["status" => "hello world"]);
print_r($statues);

Unfortunetaly I got error:
"Your credentials do not allow access to this resource"

In other issue I have read that I have to redirect user to twitter to authorize access, is there anyway to do that automatically?

**Comment by abraham** [comment]
If you want to post tweets you must be authenticated as a user. When you instantiate an instance of `TwitterOAuth` you also have to pass a user's access token and secret. If you just have a single account that you want to use and it's the user that created the Twitter app you can log into the app dashboard and generate tokens there. Otherwise you'll have to go through the full user authentication flow at least once to generate tokens. There is documentation on the user flow here https://twitteroauth.com/redirect.php
